### ISSUE TITLE
[Mark of Pride] Balancing thoughts

### ISSUE THREAD

**Issue by drsgdev** [DistractionCrab/Charm-Crab#14]
The charm feels a bit OP overall. Might be a good idea to nerf stack decay time.
I also didn't understand the logic behind it since `deltaTime` is not a fixed time period so stacks decay time is like 30s? Or 30 frames giving that the game is running at 60fps?

**Comment by DistractionCrab** [comment]
Yeah, it is meant to be 30 seconds. Time.deltaTime is Unity's way giving access to the time since the last frame update (measured in seconds). So it should follow a 30 second timer until it decays.

As for a nerf, I've considered it, but since stacks immediately get set to 0 upon taking any damage I considered that a good balance. Sure over time you could theoretically stack up some hits and walk off. But that would take a significant amount of time and you could easily lose the stacks en route. So at the moment, I think it's fine.  Maybe reduce the damage each stack gives, possibly, though I'm trying to keep this charm balanced even for very casual plays who will be getting hit a lot, not someone who knows the fights well and may only get hit once or twice. Or if it is too strong increase the charm cost to 3, if it really does end up being high tier.

I'm open to nerfing it, but I don't see a situation where it's so much stronger over other choices.

**Comment by drsgdev** [comment]
> Or if it is too strong increase the charm cost to 3, if it really does end up being high tier.
> 
> I'm open to nerfing it, but I don't see a situation where it's so much stronger over other choices.

Cost reduction might do the trick. Okay I got the time logic after doing some math :)

**Comment by DistractionCrab** [comment]
I reduced the damage bonus a bit; This'll make it less powerful over time but still allow for heavy stacking for players who can fight bosses near-hitless.

Change is in commit dcd9c5a
