### ISSUE TITLE
[Stalwart Shell] Overcharmed damage not decreased

### ISSUE THREAD

**Issue by drsgdev** [DistractionCrab/Charm-Crab#15]
Charm doesn't seem to be working when the knight is overcharmed.

**Comment by DistractionCrab** [comment]
What's the situation that you noticed this happen? I've tried it out and it's modifying damage. I tested this on one of the Devouts that deal 2 damage:

- Without charm: 2
- With Charm: 1
- Overcharmed without: 4 damage
- Overcharmed with charm: 2 damage

Note that overcharm is a multiplier after all damage has been calculated, so the 2dmg is reduced to 1 then multiplied, rather than multiplied by overcharm to 4 then reduced to three by the charm.

**Comment by DistractionCrab** [comment]
With no response I'll assume my explanation satisfied the requirements:

One thing to note, due to overcharm's mechanics, even if you have Stalwart Shell equipped and are overcharmed, regular enemies will still deal 2 damage to you.  In general this charm is only useful for bosses/harder hitting enemies as you cannot take 0 damage.

Also as a note, I don't intend to try to change it so this charm affects overcharm; Reason being this becomes much weaker against more powerful bosses in the case of overcharm (harder bosses deal 3 base damage). Effectively, this charm is currently twice as power in overcharm state in comparison.l
