### ISSUE TITLE
charms not working 

### ISSUE THREAD

**Issue by Luc1dLove** [DistractionCrab/Charm-Crab#16]
Aura of Purity, Afflicted Devourer, Soul Infused Blade can not be obtained by any means at all

**Comment by DistractionCrab** [comment]
I just tested the conditions and I was able to obtain them in a clean file. They're very specific conditions, and you may have to go through many series of dialogue because the flag only gets set when they specifically say something and not just talking to them with the items (because I haven't found a good way to setup ItemGet events for them yet), but they do seem to be working.

Is anything happening when you go and talk to the NPCs that are supposed to give them to you, or is it just no charms in your inventory are talking to them (with the right stuff done)? (I did note a bug, where I have the charm, but the icons aren't showing up, but that may be my local build due to a version change issue, which is easy to fix)

**Comment by DistractionCrab** [comment]
With no response here, I will assume that this is a non-issue. Make sure to double check the README on the main page for description for how to get these new charms. 

There will not be a popup for the item, as the event isn't an item-get event. So once you do these requirements, check your inventory.  Also note, the NPC must say the correct line (generally it's the last thing they'll say after a chain of things), with the correct item.
