### ISSUE TITLE
Bleed causes bosses to die repeatedly (possibly infinitely)

### ISSUE THREAD

**Issue by VoilaTada** [DistractionCrab/Charm-Crab#17]
Defeated Grimm with a bleed build with weaverlings and void tendrils, and every couple of seconds his death animation resets as he takes bleed damage. This locks the player in the arena since the resulting cut scene can not play until the boss finishes this animation. I noticed this happens with a few other bosses, and Grimmkin enemies as well but Grimm was the first one to lock me in the arena indefinitely. 

Charms equipped:
- Gathering Swarm
- Wayward Compass
- Sprint Master
- Shape of Unn
- Grubsong
- Dashmaster
- Sharpshadow
- Weaversong
- Heavy Blow
- Mark of Pride
- Grimmchild
- Void Tendrils
- Baulder Shell

Equipment:
- Coiled nail
- all 3 void spells
- all 3 nail arts
- Shade Cloak
- Mantis Claw
- Crystal Heart
- Monarch Wings
- Izma's Tear
- Lumafly Lantern
- Map and Quill
- Dream Nail

**Comment by DistractionCrab** [comment]
I've put a fix into the works for the moment. I made sure that without the fix the Grimmkin do not die while bleeding, and will not get stuck in a loop when the fix is there.

I'll get to testing TMG here soon, and make sure the fix works for the other situations. Feel free to let me know if you run into this issue for other enemies/bosses and I'll make sure to test it thoroughly for them.

**Comment by DistractionCrab** [comment]
Commit cc0e9c1 should fix this issue. I'll leave this open for a day or two in case something else pops up on this issue. If not, then I'll push an update to Scarab then.

**Comment by DistractionCrab** [comment]
Forgot to publish this to Scarab, it's been published in release v1.0.8

https://github.com/DistractionCrab/Charm-Crab/releases/tag/v1.0.8
