### ISSUE TITLE
In-game charm descriptions & other suggestions

### ISSUE THREAD

**Issue by argon932** [DistractionCrab/Charm-Crab#5]
Not sure if it's possible but it would be nice if the charms had more detailed descriptions describing their new changes/affects. 

It'd also be great if the mod was modular to help with mod conflicts and just let users choose what they want from the mod. I absolutely love the boss damage changes and would like to include it in all my rando runs, however, the enemy HP and nail changes makes some random runs a bit tedious (for example, if I am forced into an end game area with a lvl 0 Nail).

Some idea settings:
Boss Rebalance On/Off
Enemy Rebalance On/Off
Charm Rebalance On/Off
Nail/Spell Rebalance On/Off
New Charms On/Off

Ideally having everything set to "Off" would make the mod make no changes. I understand if this would be too much work to add but I thought I'd suggest it.

Thanks for the mod.

**Comment by DistractionCrab** [comment]
I can put some heavier descriptions in the game, currently the fully descriptions is on the main page for this mod. Though I was hoping to keep the descriptions in line with the vanilla game's descriptions, which give a high-level description. Though some descriptions will become a bit long to fit in the in-game description.

Now for the options settings, this becomes a bit of a sticky-problem; Turning off boss rebalances (which includes health values) for them means you'll be able to kill Radiance in less than 10 spell casts at full power. So I doubt that's something you want, but rather the extra damage that they do, which is feasible and I can look into making a button for that. (Just need to learn the menu part of the api).

Enemy rebalance, I'm assuming you mean health values in this case? Keep in mind that, base nail damage is 3x vanilla and enemy health values are 5x. So the different really isn't that large (unless a health value is getting bugged somewhere). Also charms scale your damage immensely, I'm not sure I see good motivation for this one. Even at +0 you should reasonably be able to fight anything as you would in the base game at +0 with very little extra difficulty (unless there's a bug). So unless there's some case out there where you're spending 10 minutes or more on a basic enemy I don't see the value in this one.

Charm Rebalance; It's kind of the point of the mod so I would say if you don't want them just uninstall the mod instead. The rebalances for enemy values are specifically to allow these charms to not just be mindlessly broken.

Nail/spell rebalances; These go hand-in-hand with health and enemy rebalances so if you did want to turn it off I can just consolidate it into the other rebalance option switches.

New Charms; I don't see a reason for this one. New charms do not overwrite anything in rando so them either being there or not isn't very helpful. Also if you want them to be there without the rebalances I'd have rebalance them for the base game, which is doable if that's what you want from it.

Though like I said, if there's a specific issue where the game becomes too tedious (like fighting a basic mob for 10+ minutes at +0) feel free to comment and I'll see what I can do. Though keep in mind for randomizer, even in base game with +0 you'll have similar problems even without this mod, as bosses/required enemies to fight at late locations (say queen's garden) is still rather challenging. Or if some enemies are getting double damage and this is the issue feel free to elaborate and I can look into making that more of a thing, since damage rebalances assumes a vanilla progression to be balanced (steady body/stalwart are fairly early and help compensate, also free healing from other charms).

**Comment by argon932** [comment]
Ah, I didn't realize things were changing THAT much. No worries then, it doesn't seem worth the headache then if it's just gonna be unbalanced, and thanks for the detailed description. 

I guess my main thing is, I would love to be able to have the boss damage increases without needing the rest of the mod. However, after reading what you said, maybe that would just be better to have in another separate mod entirely in the future. Currently I use "Hell mod" to up the damage, however that is just a flat 2x increase across the board. Bosses doing 4 hearts and normal enemies doing 2 hearts is a bit extreme, so I greatly prefer your method of making bosses feel more challenging.

**Comment by DistractionCrab** [comment]
Yeah, it is a bit complex to split this mod into separate parts for balance; With just balance changes it becomes a nightmare for vanilla mechanics. With just charm effects, it becomes way too easy (at least I think for people who'll be playing this mod).  So it'd be a full new endeavor to try to split it into pieces without remaking parts of it.

As for the boss damage, I could look into separating that out; changing enemy damage currently is *somewhat* automatic, and I know normal enemies are getting "boss" damage, but it's not simple to recognize what enemies are what due to limitations in the API. However I can look into this part, and see if it's what you'd like.

For descriptions yeah, I've been putting on vanilla descriptions a bit too much recently. So yeah, I do plan to update those, I've just been slow. As for adjusting those other charms, I would like to, but I need reasonable mechanics to attach to them. For example, I originally was going to use one of the other lifeblood charms for the mechanic, but I felt that charm was left as useless still. While at least the late ones still gave a *decent* chunk more health. However, I would like to find something to attach to the ones without changes, because you're right; They are boring/somewhat bad.

Also pride's range increase should still be there. I haven't done a lot of work to remove vanilla charm mechanics because some of them are hard coded and can't be changed. e.g. fragile greed is hard coded, but I found a hacky work-around to make it more effective. So if it's a vanilla effect assume it's in there (I'll add that to the mod description here in the near future).

Either way, if you have ideas for new charm mechanics you are welcome to suggest those and I can look at implementing them.

Cheers

**Comment by argon932** [comment]
I did find one wierd (intended?) glitch: After beating false knight and he falls through the floor, if you land on his body you take damage and die.

As for some charms, I think reducing their cost until better affects are added might be best? Personally, I use the following cost in my saves:
Long Nail = 1 (it has barely any reach compared to Mark of Pride)
Quick Focus = 2 / Deep Focus = 1. I feel like you need both of these to make big differences and deep focus by itself makes healing in fights almost impossible. Their default costs are outrageous IMO.
Joni's = 0. I think it does more harm than good, but if it's free some good players may prefer it as a take-no-damage all lifeblood charms playstyle. 
Hiveblood = 1. It's so late in the game and deep in an optional area, plus only regens 1 HP. Doesn't do much good in boss fights unless you go awhile without getting hit. For that reason, I think it should only require 1 notch. 
Lifeblood Core = 1. It only gives you life on benches and it's a very late game charm unlock. If Lifeblood heart gives you lifeblood on hit, I would keep lifeblood heart at 2 since it's extremely good for no-hit players. I feel putting this at 1 then will be a good balance of a lifeblood build for 3 charm cost (if Joni's is also at 0)
Dream Wielder... maybe 0 cost? It's pretty hard to use in combat and very situational. Or maybe have Dream Wielder also debuff the enemy which makes them take like 25% more damage for a brief period.
Glubberfly's Elegy = 1. It requires full HP and all grubs collected. It should be good and worth using.
Kingsoul/Voidheart: This feels too strong right now IMO. Voidheart shouldn't get as much regen I think?
Fury of the Fallen: I haven't tested but 25% seems like a lot.  That's double damage for only 4 masks missing. 10% seems like a good balance.

**Comment by DistractionCrab** [comment]
Here's the general list of responses per charm:

- Longnail: Currently is 1 cost, since it's not great and most just helpful with no build applications.
- Quick/Deep Focus: Both are currently 1 cost. Haven't really had much reason to change them as they are useful together (and they also have synergy with shape of unn).
- Joni's: I wouldn't call this useless; While you can't heal with it, it's a fairly massive health boost. For a cost of 1, you can toss it on and just simply focus on damage. With heavy damage builds this is actually quite useful because you're strategy is kill them before they kill you. Sure you can't heal, but that's the point of the massive boost in health. ATM, I'm content with it being 1, and personally I relegate the 0 cost charms to be something you'd want on at all times, and there's no reason to not have it (like map, gathering, and sprint master). Though experience with this charm will vary, but I've had some positive applications in the past with it (it's just not that great).
- Lifeblood: I've considered making Lifeblood core just a better version of Lifeblood Heart, though I'm not a huge fan of this as I don't like invalidating weaker charms. Though I have considered swapping them, but as you said core is very late game and depending upon how you path you may never get to use really. (for my first 100% playthrough this was close to the last charm I got), so I'm hesitant to do so. So that's why I currently have core at 1-cost because it's mostly just a health boost, but I'm still conflicted here. So may swap them at some point.
- Hiveblood: This one is deceptively strong; Since you can't regen health past 1, it seems like it won't help but it's essentially a free heal if you can manage not to get hit. However, since Voidheart/Kingsoul are now actually useable, this charm is much stronger in slower gameplay. Hiveblood already was a strong charm in White-palace for those not great at it, now it's even better. So atm it is a cost of 1, but if it were 2 it wouldn't be a wrong choice. But I'm still planning to leave it as 1 simply due to the fact that it's not so strong due to boss rebalances (getting hit for 3 damage on Super Bosses, means it will at best be a 33% dmg reduction).
- Dream Wielder: I like the debuff idea. TBH I've neglected this charm, because I just forget it exists. I'll look into implementing something for this, because it's vanilla effects are decent, but not great. TBH, it would combo well with Shaman stone in the mod, so this is a neat idea.
- GF Elegy: I still need to balance this out a bit; I haven't updated the damage yet, and haven't figured out the best way to balance it yet. With the extra healing here it could be a neat idea to have this be a central point of a high-health build (in contrast to low health builds with fury).
- King Soul/Void heart: Current soul rate is 1/2 soul per second (2 soul per 4 seconds). This means it will take 1 full minute to almost be able to cost a vanilla spell. So I don't think this is very strong, and I haven't noticed it in fights be useful. TBH, Soul Eater and Spore Shroom are just so much better for soul generation, that this is just to make void heart not be useless. In Rando/Vanilla, this will be a later item, so it won't be carrying too much either, but will be useful in enemy randos when soul is hard to get. So ATM, I'm happy with this charm.
- Fury: During my testing I ran Fury a lot; It is rather good, but it's deceptively weak at end game. The reason for this is the fact that super bosses deal 3 damage instead of 2. So even at max health, fighting them is like fighting normal enemies with 4 masks. So there is a tradeoff, and to make this more workable defensive charms (like steady body/stalwart) are costly to make up for it. Also for reference, vanilla fury is 75% at 1 health, which isn't as much as modded, but health values are raised a bit.  My real concern for this charm is more that it works for most builds, so while it's a T3 charm (costs 3 notches, and thus the most costly), it's a little too good because of that. So if I were to rebalance it would be to make it so it doesn't interact with Soul Catcher (though not sure how this will effect everything). Because Soul Catcher is currently the real strongest of the new charms, but it requires a lot of support to make it really good. So there is some thinking to be done here.

But yeah, as you said at the end there, the vanilla charm costs are not really great compared to their application. That's why there are a whole new set of charm costs, in fact most of the ones you mentioned are already updated. May not be noticeable if you're running another mod which updates charm costs. 

But I like some of the suggestions, and when I have time I'll look into implementing some of them.

Cheers

**Comment by argon932** [comment]
Silly me, I was using a randomizer and didn't see you actually nerfed charm cost across the board. I messed around in a non-randomizer game and it feels much better. (I'll need to reduce my randomizer cost factor to match this mod's new charm costs)

I did find some weird qwirks while playing today:
- The body on False Knight/Failed Champion makes you take damage if you jump on them or touch their body in any way when their knocked down. 
- Crystal Guardian makes you take damage if you try to run past them while they are inactive and sitting on the bench.
- The bleed on Heavy Blow is, well, kind of broken. Even if you don't do damage to an enemy (they block with shield, or they are a pogo-only enemy) they still take damage and the bleed stacks. But the main issue is that the bleed causes bosses to stagger. Hornet staggers if you hit her in the air, so her fight mechanics are broken if you have this charm equipped. She can't really do anything. Broken Vessel and Soul Master also get staggered constantly.  I'd say it makes the fights easier, but the bleed also kicks them out of downed states instantly making it very hard to heal. I am not sure the new affect works well unless this can be fixed.

**Comment by DistractionCrab** [comment]
I pushed an update recently through scarab; Have you updated yet? If so, does the CG and FK deaths happen on the new patch still? I made a change to fix that, but haven't had any chance to test if it worked.

As for bleed, the extra hits I can work with; I've been meaning to change it to extra damage rather than normal damage. I had forgotten about this, so I'll work on fixing this soon.

As for the shield thing, due to how blocking works it's not a trivial thing to detect when it happens. So I don't have a way right now to figure out when to not apply bleed on blocks. So this is something I'd like to fix, but currently don't have a good way to do it. So this is currently in the research phase, but I am looking into it.

**Comment by DistractionCrab** [comment]
Updating this issue with some details of what has been commited, but not released yet. Will close this issue if no further details are added after the next push to Scarab:

- Bleed is now extra damage, will no longer counter towards stagger counts. Still has an orange dmg affect to indicate it is active.
- Lifeblood Core now also has the same effect as heart, but with half as many nail strikes to activate. Both cost 2 notches, and their strikes required are 20/10 for Heart/Core respectively.
- Dreamwielder now buff's the knight's damage by 50% for 10 seconds when it hits an appropriate target.

Other issues related to this one, are being looked into currently, however I can separate those into other issues to keep things organized.

**Comment by DistractionCrab** [comment]
Closing this issue as no further comment has been made. A new update has been released and should resolve some of these issues and implement some of the new charm effects/fixes.
