### ISSUE TITLE
"Settings" tab on the mod menu to disable specific mod changes.

### ISSUE THREAD

**Issue by DamageMaximo** [DistractionCrab/Charm-Crab#6]
Hello, 
I came upon this mod and instantly fell in love with some of the features in it but also wasn't a big fan of others _**personally,**_ some changes are too radical in MY opinion and I really think it would be incredible if players could just disable some effects of the mod, the re-works to the enemy HP, boss damage, charms, soul gathering and damage are great for people looking for a very different experience, but I wish I could also just play through the normal game with the new charms without having to worry about charms working too differently to how they were before and just enjoying the new charms in the vanilla game experience.

I saw the other issue made by Argon932 and your thoughts on it, and I want to add that having gameplay customization is always a good thing, so if someone wants to be able to melt Radiance with 10 spells and that's gonna make their day a little bit better, y'know, why not? It was their choice to disable parts of the mod which would balance things out, but if it made that person's experience better for them, does it matter, that only makes said player be more satisfied with the mod.

Great mod anyway, just needs to give the user a little bit more control over what features they wish to be applied or not.

**Comment by DistractionCrab** [comment]
first in terms of melting, if that's your desire there's debug mod for it. I see little reason to turn off balances for the sake of this reason alone.

As for balance and something being *egregious* you'll need to be specific and say what you mean exactly. Because as I've played through this, I've yet to run into anything that really becomes annoying, egregious, or really bad at all. If you're talking about randomizer, then that's generally a risk you take with rando; Getting put into situations that make you fight things far above the norm. 

As you've read the other discussion you'll know how health and damage is scaled (+0 nail is 3x damage, with enemy health being 5x). This means a few more hits in the beginning and as you progress through the vanilla game you'll gain charms that make up for this (fury being one that helps with this). So as you claim things are radical, I don't really see this at all, so feel free to elaborate on this.

As for the new charms (4 of them), 1 doesn't even work without the new charm effects. 1 can work without new charms, and would be fine, and the other 2 aren't even balanced for the vanilla game. So I'd have to work on making two versions for every charm. This includes any new effects to vanilla charms, which is pointlessly time consuming. It would be better to recognize things which do not scale well and fix those instead. Not to mention, most of the new charm effects simply would be broken in the base game with how small the damage values are. I specifically chose these values to make some things harder, but as you play through the game and become power it becomes easier than the base game (unless you don't search for things).

As a side note, as you're playing through this make sure you are seeking upgrades, in terms of health, damage, charms and what-not. Ignoring them and trying to play through the game will be harder than normal. Though not much harder at +0 compared to a vanilla +0 nail run.

**Comment by DistractionCrab** [comment]
Going to leave a second comment here regarding this topic; I've added a Gameplay Guide to the README found [here](https://github.com/DistractionCrab/Charm-Crab/blob/main/README.md).

This is a reminder for how the game is structured normally, and if you are running into problems a reminder on how to deal with them as if you having problems in the vanilla game.

I'll also note, as stated in the README (now), that this is not a challenge mod or hard mode mod. This is designed to be doable by very casual players; You do not need to be a speedrunner or a No-Hit runner to be able to beat anything. But if you bash your head against a wall mindlessly without exploring you will run into rather hard situations.

**Comment by DamageMaximo** [comment]
First of all thank you very much for both detailed replies.

I didn't mean things were unbalanced and/or too hard in the overall, experience I just meant that after playing through the game with this mod on,  I might want to have this mod on for the new charms alone, and not the charm re-works and damage-reworks, but as you explained, re-balacing the charms to work well in the base game would be annoying and take more time than it's worth, and I didn't know that, I understand now. Again, thanks for the reply! Your mod is awesome and gives players a fresh experience without the need of randomizers!

**Comment by DistractionCrab** [comment]
Gotcha, that makes sense, but yes it is a bit of a pain to detach the pieces, and bit of a disappointment for a mod. Only two of the new spells would make it in there, but in the future could be worthwhile. Perhaps when I make more things that make sense standalone and have time to separate them out into individual mods maybe, but I cannot guarantee I'll be able to do that.

Either way, if you have any other suggestions feel free to make them as I'll leave this issue open for a while longer. I'm currently working on getting the next update to scarab (which will fix some bugs and add effects to some charms). However, can't say how long this will take as working with the modlinks is...  bothersome to say the least.

**Comment by DistractionCrab** [comment]
Closing this issue as no further comment has been made. A new release has been made public to scarab, so make sure to check that out for some new mechanics and bug fixes.
