### ISSUE TITLE
Gulka tanks it's projectiles

### ISSUE THREAD

**Issue by drsgdev** [DistractionCrab/Charm-Crab#9]
[Gulka enemy](https://hollowknight.fandom.com/wiki/Gulka) takes like 10 hits with it's projectile to kill. Those projectiles doesn't damage them properly due to increased health. Slash\Spell attacks deal normal damage to them.

P.S.: no idea if projectile damage on Gulka's can be specifically tweaked but would be a nice QoL change.

**Comment by DistractionCrab** [comment]
Hmm, it could be doable...  But depends on whether or not the collision for explosions is implemented in code or the FSM graph. I'll get to look at this in a bit once I have some free time, but this one could take a bit to figure out.

**Comment by DistractionCrab** [comment]
I've updated it so Gulkas and other enemies will be properly damage in accordance with the fact their health is scale when deflecting the projectiles. I'll be doing a bit more testing and cleaning of this project (since I haven't really been working on it that much), then push up an update here soon.

Feel free to add more to this if you'd like, but Gulkas should only take two hits to kill with their own projectiles (Like vanilla).

**Comment by DistractionCrab** [comment]
Fix is pushed in release dcd9c5a
